version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio
    ports:
      - "80:80"
    depends_on:
      - mongodb
    volumes:
      - ./src:/src/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/weatherApp
      NODE_ENV: production

volumes:
  mongodb_data: